# Generated by Django 4.2.2 on 2023-07-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('note', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('note', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='')),
                ('departments', models.ManyToManyField(related_name='interactions', to='workplaceUserNetwork.department')),
                ('divisions', models.ManyToManyField(related_name='interactions', to='workplaceUserNetwork.division')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaceUserNetwork.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaceUserNetwork.division')),
            ],
        ),
        migrations.CreateModel(
            name='WorkplaceUserNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_departments', to='workplaceUserNetwork.department')),
                ('comment_division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_divisions', to='workplaceUserNetwork.division')),
                ('from_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_user_networks', to='workplaceUserNetwork.user')),
                ('posting_department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posting_departments', to='workplaceUserNetwork.department')),
                ('posting_division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posting_divisions', to='workplaceUserNetwork.division')),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_user_networks', to='workplaceUserNetwork.user')),
                ('type_of_interaction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workplaceUserNetwork.interaction')),
            ],
        ),
    ]
