# Generated by Django 4.2.2 on 2023-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaceUserNetwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='divisions',
        ),
        migrations.AddField(
            model_name='interaction',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
